env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:unicorn/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - "shebangify.js"
  - "yacltrc.js"
plugins:
  - "@typescript-eslint"
  - "prefer-arrow"
  - "prettier"
  - "unicorn"
rules:
  "prefer-arrow/prefer-arrow-functions":
    - "error"
    - disallowPrototype: true
      singleReturnOnly: false
      classPropertiesAllowed: false
  "prefer-arrow-callback": "error"
  "func-style":
    - "error"
    - "expression"
  "arrow-body-style":
    - "error"
    - "as-needed"
  "no-console": "error" # We should be using the Logger, not console
  "prettier/prettier":
    - "error"
    - usePrettierrc: true
  "@typescript-eslint/explicit-function-return-type": "error"
  "unicorn/prevent-abbreviations": "off" # I want to abbreviate "parameters" as "params"
  "unicorn/prefer-node-protocol": "off" # prefixes node builtins with "node:" in the import path, this messes with Typescript
  "unicorn/no-process-exit": "off" # "Only use process.exit in CLI apps" well this is one
  "unicorn/no-array-for-each": "off" # I like Array#forEach
  "unicorn/prefer-top-level-await": "error"
  quotes:
    - "error"
    - "double"
    - avoidEscape: true
  semi:
    - "error"
    - "always"
