env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:unicorn/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - "shebangify.js"
  - "yacltrc.js"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "unicorn"
rules:
  "prettier/prettier":
    - "error"
    - usePrettierrc: true
  "@typescript-eslint/explicit-function-return-type": "error"
  "unicorn/prevent-abbreviations": "off" # I want to abbreviate "parameters" as "params"
  "unicorn/prefer-node-protocol": "off" # prefixes node builtins with "node:" in the import path, this messes with Typescript
  "unicorn/no-process-exit": "off" # "Only use process.exit in CLI apps" well this is one
  "unicorn/no-array-for-each": "off" # I like Array#forEach
  quotes:
    - "error"
    - "double"
    - avoidEscape: true
  semi:
    - "error"
    - "always"
